[colors.bright]
black = "#323652"
blue = "#AECBCD"
cyan = "#C2D7D4"
green = "#A6BA96"
magenta = "#C8A2C1"
red = "#CD664D"
white = "#DFDCCB"
yellow = "#DCDF82"

[colors.normal]
black = "#49463D"
blue = "#86B7B9"
cyan = "#9AC3C0"
green = "#5F7162"
magenta = "#B3816E"
red = "#B95239"
white = "#B7B4A3"
yellow = "#C8B764"

[colors.primary]
background = "#4D4B41"
foreground = "#DAD3BA"

[font]
size = 14
offset = {x=0,y=1}

[font.bold]
family = "monospace"
style = "Bold"

[font.normal]
family = "monospace"
style = "Regular"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 2000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/bash"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
